### PR TITLE
attempt to load json files locally

### PR DESCRIPTION
**Pull request by hdhoang**
We could automatically save the files too, but I feel iffy about modifying users' filesystem permanently. What do you think?

### CODE REVIEW

**Comment by pietroalbini** [comment]
Caching the files automatically sounds good to me. Maybe we could save them in a `cache` subdirectory to allow for an easy `rm -rf cache`?

**Comment by hdhoang** [comment]
I thought that `pr-*` is good enough, but `cache` is more explicit and allow for wierd experiment names too. I'll switch over that way.

**Comment by pietroalbini** [comment]
Thanks!

**Comment by hdhoang** [comment]
whoops, could you cherry-pick https://github.com/hdhoang/crater-tree/commit/eb1041885993e4545023ac58b3bab56736bd1500 too? It helps with this error case:

```shell
> chmod -r cache/pr-49799/results.json

> ....
error: failed to load results from crater
  caused by: Permission denied (os error 13)
# after
> ...
error: failed to load results from crater
  caused by: results.json
  caused by: Permission denied (os error 13)

**Pull request merged**
